### ISSUE TITLE
Suggestion: use reactions(emojis) to link color in game 

### ISSUE THREAD

**Issue by Talh21** [pedrofracassi/amongcord#26] opened 2020-09-22 08:56 UTC
I think that it could be more easier for users to just click on the color. Maybe after the sync/newgame(that I think it should be unite), the bot will present all colors options so the players could just click on the emoji and they will join with their color much more easily. It could be less annoying than typing `,join <color>`

**Comment by iiftekhar** [comment] 2020-09-22 10:11
If aliases begin to work, I think it won't be that much annoying.

**Comment by Talh21** [comment] 2020-09-22 13:13
> If aliases begin to work, I think it won't be that much annoying.

Sorry but to add every friend of mine is annoying even with the aliases(to long -and "forcejoin" is not so useful) . My friends are untech guys and they are very lazy to make this. I think that if the reaction linking would be added it will be very useful and easy for them to understand. That's my opinion tho.

**Comment by pedrofracassi** [comment] 2020-09-22 20:03
Dupe of #13

**Closed as completed by pedrofracassi** 2020-09-22 20:03 UTC
Labels: suggestion
